#ifndef MPP_CONFIG_HPP
#define MPP_CONFIG_HPP

#define MPP_MAXIMUM_NUMBER_OF_DIMENSIONS 100000000
#define MPP_MAXIMUM_NUMBER_OF_SAMPLES_PER_RUN_SAMPLER_CALL 1000000
#define MPP_CLASSIC_HAMILTONIAN_MAX_NUM_STEPS 100

#endif // MPP_CONFIG_HPP
